# Generated by Django 3.2.5 on 2021-07-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tcname', models.CharField(db_column='tcName', max_length=150)),
                ('osname', models.CharField(db_column='osName', max_length=200)),
                ('fullname', models.CharField(db_column='fullName', max_length=255)),
                ('defgroup', models.CharField(blank=True, db_column='defGroup', max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('lastlogin', models.DateTimeField(blank=True, db_column='lastLogin', null=True)),
                ('licenseserver', models.CharField(db_column='licenseServer', max_length=100)),
                ('licenselevel', models.IntegerField(blank=True, db_column='licenseLevel', null=True)),
                ('site', models.CharField(max_length=45)),
                ('deactreason', models.CharField(blank=True, db_column='deactReason', max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
