# Generated by Django 3.2.5 on 2021-07-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupmembers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tcname', models.CharField(db_column='tcName', max_length=150)),
                ('info', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=150)),
                ('site', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Пользователь группы',
                'verbose_name_plural': 'Пользователи группы',
                'db_table': 'groupmembers',
                'managed': False,
            },
        ),
    ]
