# Generated by Django 3.2.5 on 2021-07-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_groupmembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tcgroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('parentname', models.CharField(blank=True, db_column='parentName', max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('volume', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.CharField(max_length=45)),
                ('roles', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tcgroups',
                'managed': False,
            },
        ),
    ]
