# Generated by Django 3.2.5 on 2021-07-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20210727_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
